### ISSUE TITLE
Playwright with Github Actions

### ISSUE THREAD

**Issue by depapp** [bearmentor/bearmentor.com#15]
# Chore

## Describe the chore

@mhaidarhanif @zainfathoni how about implementing `github actions` for the UI test?

**Comment by mhaidarhanif** [comment]
@depapp You can implement it if you want to. @zainfathoni knows better.

I have less experience in running e2e UI tests in GitHub Actions.

The goal is to make sure if there's the GitHub Actions running, the deployment process is still around 1-2 minutes. So not to reduce the development speed for now.

**Comment by depapp** [comment]
@mhaidarhanif i think we can separate the vercel deployment & github actions ui e2e test so it won't affect the vercel deployment time.

@mhaidarhanif @zainfathoni i've tried to implement it on my own bearmentor fork
you can check it here https://github.com/depapp/bearmentor/actions 

here's the config file 
```yaml
name: UI E2E Test using Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Prisma DB Push        
      run: pnpm db:push

    - name: Build Project
      run: pnpm build

    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - run: pnpm exec playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Run Playwright tests
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```
